# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 17 Feb 2014 15:09:39 +0000
*               @ALL          0
*               @user         8
start	@ALL	1
wiki:navigation	@ALL	1
wiki:*	@ALL	1
