<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jlopes
 * Date: Mon, 17 Feb 2014 16:18:09 +0000
 */

$conf['title'] = 'MASSim2Dev - Masters Thesis - João Lopes';
$conf['template'] = 'vector';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['vector']['vector_sitenotice'] = 0;

// end auto-generated content
