backend:
  name: git-gateway
  branch: master

media_folder: 'assets' # Media files will be stored in the repo under static/images/uploads

collections:
  - name: 'career'
    label: 'Career' # Used in the UI
    folder: 'data/career' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string', required: false }
      - { label: 'Organization', name: 'org', widget: 'string' }
      - { label: 'Website', name: 'website', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'string' }    
      - { label: 'Period', name: 'period', widget: 'string' }    
      - { label: 'Tags', name: 'tags', widget: 'string', required: false }    
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'posts'
    label: 'Posts'
    folder: 'data/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'string' }
      - { label: 'Original source', name: 'original_source', widget: 'string', required: false }
      - { label: 'Original link', name: 'original_link', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string', required: false }
      - { label: 'Tags', name: 'tags', widget: 'string', required: false }    
      - { label: 'Body', name: 'body', widget: 'markdown' }
